
---
- name: ServiceNow Close Incident
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:

  - name: Update ServiceNow ticket to close
    servicenow.itsm.api:
      instance:
        host: "{{ snow_instance }}"
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
      resource: incident
      action: patch
      sys_id: "{{ inc_sysid }}"
      data:
        work_notes: "This request has been resolved using Ansible to reissue SSL Certificate. Run ID: {{ tower_job_id }}"
        close_code: Resolved by caller
        close_notes: resolved by ansible
        incident_state: 7
    register: snow_var

