---
- name: Create a new change record in ServiceNow and link an incident
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create change record
      community.servicenow.snow_record:
        instance: "{{ instance }}"
        table: "change_request"
        username: "{{ username }}"
        password: "{{ password }}"
        data:
          short_description: "Generate new SSL certificate "
          description: "This change was created via Ansible playbook for the purpose of renewing ssl certificate for rippademo.com"
          category: "Software"
          risk: "moderate"
          impact: "low"
      register: change_result

    - name: Display change result
      debug:
        var: change_result

    - name: Link incident to change record
      community.servicenow.snow_record:
        instance: "{{ instance }}"
        table: "incident"
        username: "{{ username }}"
        password: "{{ password }}"
        query:
          number: "{{ inc_number }}"  # You need to provide the incident number
        data:
          change_request: "{{ change_result.record.sys_id }}"
      register: incident_result

    - name: Display incident update result
      debug:
        var: incident_result