
---
- name: ServiceNow Create Incident
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
  - name: Create Incident
    servicenow.itsm.incident:
      instance:
        host: "{{ snow_instance }}"
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
      state: new
      short_description: "{{ short }}"
      urgency: 2
      impact: 2
      description: 
        "{{ description }}"
      other:
        assigned_to: Andrew Och
        caller_id: AAP
    register: new_incident

  - name: set stats
    ansible.builtin.set_stats:
      inc_number: "{{ new_incident.record.number }}"
      inc_sysid: "{{ new_incident.record.sys_id }}"
