---
- name: Create a change record in ServiceNow and attach an incident
  hosts: localhost
  gather_facts: no

  # vars:
  #   incident_number: "INC0010001"  # Replace with your incident number
  #   change_request_data:
  #     short_description: "Generate new SSL Cert"
  #     description: "creating a new SSL certificate for rippademo.com"
  #     category: "Software"
  #     priority: "2"

  tasks:
    - name: Create change request
      servicenow.itsm.change_request:
        instance:
          host: "{{ instance }}"
          username: "{{ username }}"
          password: "{{ password }}"
        type: normal
        state: new
        requested_by: AAP
        short_description: "{{ inc_number }}"
        description: "creating a new SSL certificate for {{ url }}, to resolve: {{ error }}"
        assignment_group: Software
        priority: moderate
        risk: low
      register: change_result

    # - name: Create change request
    #   servicenow.itsm.change_request:
    #     instance:
    #       host: "{{ instance }}"
    #       username: "{{ username }}"
    #       password: "{{ password }}"
    #     type: normal
    #     state: new
    #     requested_by: AAP
    #     short_description: "{{ inc_number }}"
    #     description: "creating a new SSL certificate for rippademo.com"
    #     priority: moderate
    #     risk: low
    #   register: change_result

    - name: set stats
      ansible.builtin.set_stats:
        data:
          chg_number: "{{ change_result.record.number }}"
          chg_sysid: "{{ change_result.record.sys_id }}"

    - name: Update ServiceNow ticket to indicate start
      servicenow.itsm.api:
        instance:
          host: "{{ instance }}"
          username: "{{ username }}"
          password: "{{ password }}"
        resource: incident
        action: patch
        sys_id: "{{ inc_sysid }}"
        data:
          work_notes: "{{ change_result.record.number }} Raised via Ansible."
      register: snow_var
    # - name: Link incident to change record
    #   servicenow.itsm.snow_record:
    #     instance: "{{ instance }}"
    #     table: "task_rel_ci"
    #     username: "{{ username }}"
    #     password: "{{ password }}"
    #     data:
    #       type: "fixed by"
    #       change_request: "{{ change_result.record.sys_id }}"
    #       incident: "{{ inc_number }}"
    #   register: link_result
    # - name: Attach change request to incident
    #   servicenow.itsm.incident:
    #     instance:
    #       host: "{{ instance }}"
    #       username: "{{ username }}"
    #       password: "{{ password }}"
    #     number: "{{ inc_number }}"
    #     data:
    #       change_request: "{{ change_result.record.sys_id }}"
    #   register: update_result