---
- name: create rhel9 ec2 instance
  hosts: all

  tasks:
  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
      name: "{{ vm_name }}"
      key_name: "rhlab"
      vpc_subnet_id: subnet-0498e176e01ac3af1
      instance_type: t2.small
      security_group: launch-wizard-1
      network:
        assign_public_ip: true
      image_id: ami-0d77c9d87c7e619f9  #rhel 9 AMI
      region: us-east-2
    delegate_to: localhost
    register: info
  
  - name: get public dns name of new ec2 instance
    amazon.aws.ec2_instance_info:
      instance_ids: "{{ info.instance_ids }}"
    delegate_to: localhost
    register: ec2_info

  - name: debug
    debug: 
      var: ec2_info
  
  
    
