---
- name: Create a change record in ServiceNow and attach an incident
  hosts: localhost
  gather_facts: no

  vars:
    incident_number: "INC0010001"  # Replace with your incident number
    change_request_data:
      short_description: "Generate new SSL Cert"
      description: "creating a new SSL certificate for rippademo.com"
      category: "Software"
      priority: "2"

  tasks:
    - name: Create change request
      servicenow.itsm.change_request:
        instance: "{{ instance }}"
        username: "{{ username }}"
        password: "{{ password }}"
        data: "{{ change_request_data }}"
      register: change_result

    - name: Attach change request to incident
      servicenow.itsm.incident:
        instance: "{{ instance }}"
        username: "{{ username }}"
        password: "{{ password }}"
        number: "{{ inc_number }}"
        data:
          change_request: "{{ change_result.record.sys_id }}"
      register: update_result

    - name: Debug change request result
      debug:
        var: change_result

    - name: Debug incident update result
      debug:
        var: update_result