---
- name: test porkbun api
  hosts: localhost

  tasks:

  - name: get DNS records
    ansible.builtin.uri:
      url: "https://porkbun.com/api/json/v3/dns/retrieve/{{ domain_name }}"
      method: POST
      return_content: true
      body:
        secretapikey: "{{ dns_secret_key }}"
        apikey: "{{ dns_api_key }}"
      body_format: json
    register: results
  
  - name: print request results
    debug:
      var: results