---
- name: renew certs using certbot role
  hosts: "{{ hosts }}"

  tasks:
  - name: enable EPEL repo
    ansible.builtin.dnf:
      disable_gpg_check: true
      name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm'
      state: present

  - name: run certbot role
    include_role:
      name: geerlingguy.certbot
  
  - name: force renew
    ansible.builtin.shell: sudo certbot renew --force-renewal
    tags: force
