
---
- name: ServiceNow Create Incident
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:

  - name: Update ServiceNow ticket to indicate start
    servicenow.itsm.api:
      instance:
        host: "{{ instance }}"
        username: "{{ username }}"
        password: "{{ password }}"
      resource: incident
      action: patch
      sys_id: "{{ ansible_eda.event.sys_id }}"
      data:
        work_notes: "TVT Test has failed: {{ error }}"
    register: snow_var
  - name: Gather journal /var/log/messages
    ansible.builtin.shell: "echo 'httpd.service - The Apache HTTP Server Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; preset: disabled)' > /tmp/incident_journal.log"
    register: journal_log
  - name: Attach the log files
    servicenow.itsm.attachment_upload:
      instance:
        host: "{{ instance }}"
        username: "{{ username }}"
        password: "{{ password }}"
      table_name: incident
      table_sys_id: "{{ inc_sysid }}"
      attachments:
        - path: "/tmp/incident_journal.log"
          name: "incident_journal.log"
